### ISSUE TITLE
Consider caching output of `deno info`

### ISSUE THREAD

**Issue by bartlomieju** [itsdouges/vite_plugin_deno_resolve#1]
I suggest to cache the output of `deno info` when it is called during `resolve`/`load` stage. If the root module that was passed to `deno info` is loaded then all of its imports (and imports of imports) would be loaded as well, so it seems wasteful to call out to `deno info` for every single file, instead we could reach out for the information that was already retrieved in the first call to `deno info`. 

I think it's fine to never invalidate this cache as Vite will reload on file change which (if I'm not mistaken) should invalidate the cache.

**Comment by itsdouges** [comment]
Thanks definitely a good point. Right now I'm just in the make it work path (I've been adding and deleting a lot of code recently to figure out some stuff). Will definitely cache after everything is working 😄.

**Comment by itsdouges** [comment]
This is done.
